# Generated by Django 5.0 on 2024-05-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game', models.CharField(max_length=100)),
                ('track', models.CharField(max_length=100)),
                ('car', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('next_closest_time', models.TimeField()),
                ('difference', models.DurationField()),
            ],
        ),
    ]
