# Generated by Django 5.0 on 2024-05-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBoards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='next_closest_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='time',
            field=models.DurationField(),
        ),
    ]
