# Generated by Django 5.0 on 2024-05-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBoards', '0002_alter_leaderboard_next_closest_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='difference',
            field=models.DurationField(db_column='difference'),
        ),
        migrations.RenameField(
            model_name='leaderboard',
            old_name='difference',
            new_name='_difference',
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='next_closest_time',
            field=models.DurationField(db_column='next_closest_time'),
        ),
        migrations.RenameField(
            model_name='leaderboard',
            old_name='next_closest_time',
            new_name='_next_closest_time',
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='time',
            field=models.DurationField(db_column='time'),
        ),
        migrations.RenameField(
            model_name='leaderboard',
            old_name='time',
            new_name='_time',
        ),
    ]
