# Generated by Django 5.0 on 2024-05-13 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBoards', '0003_alter_leaderboard_difference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='_difference',
            field=models.DurationField(db_column='difference', default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='_next_closest_time',
            field=models.DurationField(db_column='next_closest_time', default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='_time',
            field=models.DurationField(db_column='time', default=datetime.timedelta(0)),
        ),
    ]
