# Generated by Django 5.0 on 2024-05-13 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBoards', '0004_alter_leaderboard__difference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='_difference',
            field=models.DurationField(blank=True, db_column='difference', default=datetime.timedelta(0), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='_next_closest_time',
            field=models.DurationField(blank=True, db_column='next_closest_time', default=datetime.timedelta(0), editable=False, null=True),
        ),
    ]
