# Generated by Django 5.0 on 2024-05-13 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBoards', '0005_alter_leaderboard__difference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('settings', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeBoards.game')),
            ],
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.AddField(
            model_name='car',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeBoards.game'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeBoards.car'),
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeBoards.track'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['track', 'car', 'user'], name='TimeBoards__track_i_3ed9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['track', 'car'], name='TimeBoards__track_i_e9efd5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardentry',
            unique_together={('track', 'car', 'user')},
        ),
    ]
