# Generated by Django 5.0 on 2024-05-13 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBoards', '0006_car_game_leaderboardentry_track_delete_leaderboard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameIndex(
            model_name='leaderboardentry',
            new_name='TimeBoards__track_i_835dfb_idx',
            old_name='TimeBoards__track_i_3ed9b6_idx',
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeBoards.person'),
        ),
    ]
