# Generated by Django 5.0 on 2024-05-14 00:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBoards', '0008_leaderboardentry_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='logged_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
