# Generated by Django 5.0 on 2024-05-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBoards', '0009_leaderboardentry_logged_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='logged_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
