# Generated by Django 5.0 on 2024-05-14 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBoards', '0010_alter_leaderboardentry_logged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TimeBoards.track'),
            preserve_default=False,
        ),
    ]
