# Generated by Django 5.0 on 2024-05-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeBoards', '0012_achievement_car_image_track_configurations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='track',
        ),
        migrations.AddField(
            model_name='track',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='tracks', to='TimeBoards.car'),
        ),
    ]
